heat_template_version: 2014-10-16

description: HA server pair resource type

parameters:
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: cirros0.3.2
  flavor:
    type: string
    label: Flavor
    description: Flavor to be used
    default: m1.tiny
    constraints:
      - allowed_values: [ m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge ]
        description: Value must be one of m1.tiny, m1.small, m1.medium, m1.large or m1.xlarge.    
  private_net:
    type: string
    description: Id of the private network for the compute server
    default: preservedNetwork
  private_subnet:
    type: string
    description: Id of the private sub network for the compute server
    default: preservedSubnet
  public_net:
    type: string
    description: Id of the public network for the compute server
    default: pub_net
  security_group_id:
    type: string
    description: Security group id
    default: preservedSecurityGroup
  server_postfix:
    type: string
    description: The postfix of the server name

resources:
  server1:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: pref%-postf%
          params:
            "pref%": Jedi
            "postf%": { get_param: server_postfix }
      key_name: preservedSshKey
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: server1_port }

  server2:
    type: OS::Nova::Server
    properties:
      name:
        str_replace:
          template: pref%-postf%
          params:
            "pref%": Sith
            "postf%": { get_param: server_postfix }
      key_name: preservedSshKey
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: server2_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      fixed_ips:
        - subnet: { get_param: private_subnet }
      security_groups: [{ get_param: security_group_id }]

  server2_port:
    type: OS::Neutron::Port
    properties:
      network: { get_param: private_net }
      fixed_ips:
        - subnet: { get_param: private_subnet }
      security_groups: [{ get_param: security_group_id }]

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server1_port }

  server2_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: public_net }
      port_id: { get_resource: server2_port }

outputs:
  floating_ip1:
    description: The floating IP of the first server
    value: { get_attr: [server1_floating_ip, floating_ip_address] }
  floating_ip2:
    description: The floating IP of the second server 
    value: { get_attr: [server2_floating_ip, floating_ip_address] }
