heat_template_version: 2014-10-16

description: HA server pair resource type

parameters:
  image_id:
    type: string
    label: Image ID
    description: Image to be used for compute instance
    default: cirros0.3.2
  flavor:
    type: string
    label: Flavor
    description: Flavor to be used
    default: m1.small
    constraints:
      - allowed_values: [ m1.tiny, m1.small, m1.medium, m1.large, m1.xlarge ]
        description: Value must be one of m1.tiny, m1.small, m1.medium, m1.large or m1.xlarge.    
  private_net_id:
    type: string
    description: Id of the private network for the compute server
  private_subnet_id:
    type: string
    description: Id of the private sub network for the compute server
  public_net_id:
    type: string
    description: Id of the public network for the compute server 
  security_group_id:
    type: string
    description: Security group id

resources:
  server1:
    type: OS::Nova::Server
    properties:
      key_name: preservedSshKey
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: server1_port }

  server2:
    type: OS::Nova::Server
    properties:
      key_name: preservedSshKey
      image: { get_param: image_id }
      flavor: { get_param: flavor }
      networks:
        - port: { get_resource: server2_port }

  server1_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group_id }]

  server2_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: private_net_id }
      fixed_ips:
        - subnet_id: { get_param: private_subnet_id }
      security_groups: [{ get_param: security_group_id }]

  server1_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: server1_port }

  server2_floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: { get_param: public_net_id }
      port_id: { get_resource: server2_port }
